### ISSUE TITLE
How do I get it up and running? - Also future noob checklist -

### ISSUE THREAD

**Issue by abhiii5459** [notwaldorf/emoji-translate#15]
@notwaldorf 
Env: Windows 10

Node version present - v.6.7.0 (older versions (4+) also probably work)
Installed bower -  **npm install -g bower**
Installed emoji-translate -  **bower install emoji-translate**

How do I start it as a local server? 
node emoji-translate.js just seems to complete and close. Isn't even running in the background. What should I be doing?

**Comment by notwaldorf** [comment]
If you just want to play with the demo, start a local server (`Python -m SimpleHttpServer` is the simplest), and then navigate to the `Index.tml`

**Comment by notwaldorf** [comment]
Hope this helps!

**Comment by abhiii5459** [comment]
Thank you so much!! Damn. I thought about starting a SimpleHTTPServer and trying it out, but then I was like.. It can't be just that ..What if there's more to it :D Thanks again :) Let's see if I can suggest some modifications to it. I love emojis :)

**Comment by abhiii5459** [comment]
This is resolved ^_^. Closing.
