### ISSUE TITLE
Keyword missing

### ISSUE THREAD

**Issue by sumanjeetsandhu** [notwaldorf/emoji-translate#18]
I typed in " Oh!!! The bow-tie is nice but does not match with suit."
The only emoji came up was Bow-tie, I was expecting 'thumbs up' emoji to come up instead of 'nice'.
For 'suit', the emoji came up were not relevant.

**Comment by notwaldorf** [comment]
Thanks for trying it out! The mappings are actually taken from https://github.com/muan/emojilib, which is open source -- you can send a PR for those keywords to be added! :)

(closing, since this is an issue upstream)
