### ISSUE TITLE
Missing keywords

### ISSUE THREAD

**Issue by sumanjeetsandhu** [notwaldorf/emoji-translate#19]
![image](https://cloud.githubusercontent.com/assets/23004092/23310326/1c667fd4-faaa-11e6-93cf-6a7737d14429.png)

Tried typing in few words, but nothing came up for "day"and"ice-cream" , on the other hand when I type in ice-cream without "-" sign , nothing comes up.

For day, sun can be used., as I saw for night moon was coming up.

**Comment by notwaldorf** [comment]
The mappings are actually taken from https://github.com/muan/emojilib, which is open source -- you can send a PR for those keywords to be added! :)
