### ISSUE TITLE
Typing "honey" brings up a been and visa-versa

### ISSUE THREAD

**Issue by mikestreety** [notwaldorf/emoji-translate#22]
If i type honey, a bee comes up,
If i type bee, a honey pot comes up.

🤷‍♂️ 

👍 💼 though, it's 🇬🇧!

(i've just discovered typing "great" brings up the "Great Britain" flag 🥇 

![screen shot 2017-06-14 at 14 48 56](https://user-images.githubusercontent.com/354085/27135603-db55e72e-5110-11e7-9fcc-7ef7bfdf7fa1.png)

**Comment by gabru-md** [comment]
this definitely is a BUG XD

**Comment by notwaldorf** [comment]
This uses github.com/muan/emojilib behind the scenes for the mapping of keywords to emoji, so if there's any keywords problems they should be filed there :)

**Comment by mikestreety** [comment]
Done :) https://github.com/muan/emojilib/issues/129
