### ISSUE TITLE
Includes the space in the emoji

### ISSUE THREAD

**Issue by Haroenv** [notwaldorf/emoji-translate#8]
In Chrome this leads to a large space that can be removed via inspect element, in Safari however, this space can't be removed manually, but the large padding is gone when not using `AppleColorEmoji` (this also fixes the spacing in Chrome)

**Comment by notwaldorf** [comment]
Argh, if I remember correctly, not using `AppleColorEmoji` means numbers aren't displayed correctly. The two squares should actually be 1️⃣:

<img width="74" alt="screen shot 2016-02-02 at 12 27 45 pm" src="https://cloud.githubusercontent.com/assets/1369170/12763288/6ebb5bc6-c9a8-11e5-94c5-afa3dc08496d.png">

I think that's probably a Chrome bug buuuuut it's still pretty sad. Let me see if removing the spaces but keeping the font works out.

**Comment by Haroenv** [comment]
Hmm, seems like a jar of spiders

**Comment by notwaldorf** [comment]
I'll take a look tonight. I'm 98% sure just not adding the space is fiiiiiiiine

**Comment by notwaldorf** [comment]
Fixed in https://github.com/notwaldorf/emoji-translate/commit/b3ac38759b77b882eca16e1a9430373340409745
